### ISSUE TITLE
memtestCL_core.h:45:13: fatal error: CL/opencl.h: No such file or directory

### ISSUE THREAD

**Issue by jjziets** [ihaque/memtestCL#12]
root@C.683872:~/memtestCL$ make -f Makefiles/Makefile.linux64
g++ -c -O2 -Wall -DLINUX -I/include -L-L/lib/x86_64 -o memtestCL_core.o memtestCL_core.cpp
In file included from memtestCL_core.cpp:14:
memtestCL_core.h:45:13: fatal error: CL/opencl.h: No such file or directory
   45 |    #include <CL/opencl.h>
      |             ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefiles/Makefile.linux64:31: memtestCL_core.o] Error 1

I'm on ubuntu 20.04 with nvidia NVIDIA-SMI 455.23.04  cudu 11.1

how do i fix this?

**Comment by mirh** [comment]
Install some kind of opencl header I guess?
https://packages.ubuntu.com/focal/opencl-c-headers

**Comment by ihaque** [comment]
Yes, you'll likely need to `apt install opencl-headers`.
